#!/bin/bash

set -ex

# Define the directories to exclude
EXCLUDE_DIRS=(".git" "examples" ".binder")

# Convert the array to a pattern for find
EXCLUDE_PATTERN=$(printf "! -name %s -prune " "${EXCLUDE_DIRS[@]}")

# Find and remove everything except the excluded directories
find . -maxdepth 1 -mindepth 1 \( $EXCLUDE_PATTERN \) -exec rm -rf {} +

# Move everything from the examples folder to the current directory
mv examples/* .

# Remove the now-empty examples folder
rmdir examples

echo "Directory cleaned up."